on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build Debug APK & IPA"
jobs:
  build:
    name: Build Debug APK & IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Build debug APK
      - run: flutter build apk --debug

      # Build iOS debug version
      - run: flutter build ios --no-codesign

      # Archive iOS debug app as .ipa
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r app-debug.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-debug.apk,build/ios/iphoneos/app-debug.ipa"
          tag: debug-v1.0.${{ github.run_number }}
          token: ${{ secrets.GH_TOKEN }}
