name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          targetBranch: "gh-pages"  # Ensure this branch exists or will be created
          baseHref: "/"  # Adjust based on your project needs
